let S="";
const $=x=>document.getElementById(x);
async function api(u,o={}){let r=await fetch(u,{...o,headers:{"Content-Type":"application/json","x-admin-session":S,...(o.headers||{})}}),d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
async function login(){try{let d=await api("/api/admin/login",{method:"POST",body:JSON.stringify({username:$("u").value,password:$("p").value})});S=d.session;sessionStorage.S=S;$("login").classList.add("hide");$("app").classList.remove("hide");await all()}catch(e){$("msg").textContent="❌ "+e.message}}
function logout(){S="";sessionStorage.removeItem("S");$("app").classList.add("hide");$("login").classList.remove("hide")}
function show(id){["dashboard","users","tasks","withdrawals","notices"].forEach(x=>$(x).classList.add("hide"));$(id).classList.remove("hide");$("title").textContent=id[0].toUpperCase()+id.slice(1);if(id==="users")users();if(id==="tasks")tasks();if(id==="withdrawals")withdrawals();if(id==="notices")notices()}
async function all(){await stats();await users();await tasks();await withdrawals();await notices()}
async function stats(){let d=await api("/api/admin/stats");$("su").textContent=d.users;$("sa").textContent=d.activeUsers;$("sw").textContent=d.pendingWithdrawals;$("sp").textContent=d.paidWithdrawals}
async function users(){let a=await api("/api/admin/users");$("ut").innerHTML=a.length?`<div class="table"><table><tr><th>Name</th><th>User ID</th><th>Balance</th><th>Total</th><th>Status</th><th>Action</th></tr>${a.map(x=>`<tr><td>${e(x.name)}</td><td>${e(x.user_id)}</td><td>৳${x.balance}</td><td>৳${x.total_income}</td><td>${x.status}</td><td><button onclick="status(${x.id},'${x.status}')">${x.status==="active"?"Block":"Activate"}</button> <button onclick="bal(${x.id})">Balance</button></td></tr>`).join("")}</table></div>`:"No users yet."}
async function status(id,s){await api("/api/admin/users/"+id+"/status",{method:"PATCH",body:JSON.stringify({status:s==="active"?"blocked":"active"})});users();stats()}
async function bal(id){let n=prompt("Balance change (+/-):","50");if(n===null)return;await api("/api/admin/users/"+id+"/balance",{method:"POST",body:JSON.stringify({amount:Number(n)})});users()}
async function tasks(){let a=await api("/api/admin/tasks");$("tk").innerHTML=a.length?`<div class="table"><table><tr><th>Title</th><th>Reward</th><th>URL</th><th>Active</th><th></th></tr>${a.map(x=>`<tr><td>${e(x.title)}</td><td>৳${x.reward}</td><td>${e(x.url)}</td><td>${x.active?"Yes":"No"}</td><td><button onclick="taskState(${x.id},${x.active})">${x.active?"Disable":"Enable"}</button></td></tr>`).join("")}</table></div>`:"No tasks yet."}
async function addTask(){await api("/api/admin/tasks",{method:"POST",body:JSON.stringify({title:$("tt").value,reward:Number($("tr").value),url:$("tu").value})});$("tt").value=$("tr").value=$("tu").value="";tasks()}
async function taskState(id,a){await api("/api/admin/tasks/"+id,{method:"PATCH",body:JSON.stringify({active:!a})});tasks()}
async function withdrawals(){let a=await api("/api/admin/withdrawals");$("wt").innerHTML=a.length?`<div class="table"><table><tr><th>User</th><th>Method</th><th>Account</th><th>Amount</th><th>Status</th><th></th></tr>${a.map(x=>`<tr><td>${e(x.user_id)}</td><td>${e(x.method)}</td><td>${e(x.account)}</td><td>৳${x.amount}</td><td>${x.status}</td><td><select onchange="wstate(${x.id},this.value)"><option>pending</option><option>approved</option><option>paid</option><option>rejected</option></select></td></tr>`).join("")}</table></div>`:"No withdrawal requests yet."}
async function wstate(id,s){await api("/api/admin/withdrawals/"+id,{method:"PATCH",body:JSON.stringify({status:s})});withdrawals();stats()}
async function notices(){let a=await api("/api/admin/notices");$("ntable").innerHTML=a.length?a.map(x=>`<article><b>${e(x.title)}</b><p>${e(x.body)}</p><button onclick="nstate(${x.id},${x.active})">${x.active?"Disable":"Enable"}</button></article>`).join(""):"No notices yet."}
async function addNotice(){await api("/api/admin/notices",{method:"POST",body:JSON.stringify({title:$("nt").value,body:$("nb").value})});$("nt").value=$("nb").value="";notices()}
async function nstate(id,a){await api("/api/admin/notices/"+id,{method:"PATCH",body:JSON.stringify({active:!a})});notices()}
function e(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
addEventListener("load",()=>{S=sessionStorage.S||"";if(S){$("login").classList.add("hide");$("app").classList.remove("hide");all().catch(logout)}})
